# Generated by Django 4.2.6 on 2023-10-19 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_campus_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='course_id',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='year',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
